### ISSUE TITLE
Incorrect repology link for python packages

### ISSUE THREAD

**Issue by Moredread** [ryantm/nixpkgs-update#104]
E.g. in https://github.com/NixOS/nixpkgs/pull/54106 the link to repology is incorrect, as it includes the python version part of the package name, i.e. https://repology.org/metapackage/python3.7-jsonrpclib-pelix/versions instead of https://repology.org/metapackage/jsonrpclib-pelix/versions.

I'm not sure it is the same issue as #74

**Comment by FRidh** [comment]
Repology now redirects.
