### ISSUE TITLE
Make nixpkgs-update reproducable

### ISSUE THREAD

**Issue by bobvanderlinden** [ryantm/nixpkgs-update#111]
Currently the README states to recreate the `shell.nix` from the Cabal file. This generates a file that points to `nixpkgs` channel.

On my system this channel points to some version of `nixos-18.09` by default. On that version `typed-process` is on version `0.2.3.0`. `nixpkgs-update` uses `readProcessInterleaved_` from `typed_process`. `typed-process-0.2.3.0 version does not support `readProcessInterleaved_` as it was introduced in `typed-process-0.2.4.0` (http://hackage.haskell.org/package/conduit-extra-1.3.1.1/docs/Data-Conduit-Process-Typed.html#v:readProcessInterleaved_).

Due to this difference in environment I was not able to build `nixpkgs-update` by following the instructions.

To make a project reproducible I usually add the explicit version of nixpkgs to shell.nix:

```
{ nixpkgs-tarball ? builtins.fetchTarball {
  name = "nixpkgs-unstable";
  url = "https://releases.nixos.org/nixpkgs/nixpkgs-19.09pre173445.796a8764ab8/nixexprs.tar.xz";
  sha256 = "04frhzc74xx2zsq7gbbnnh2d24hnl58i2sd24hdbwx8kyyh386xd";
}, nixpkgs ? import nixpkgs-tarball {}, compiler ? "default", doBenchmark ? false }:
```

For nixpkgs-update this would look like: https://gist.github.com/bobvanderlinden/ed272cb78f72b1b177c54519aa507421

**Comment by ryantm** [comment]
Sounds good. I'd also like to find some way to improve the nix-run invocation to not require specifying `gitAndTools.hub`, `gist`, `jq`, and  `tree` are available. The main reason I hadn't done this yet was because  I want to be able to regenerate the cabal file when I add a new dependency.

**Comment by ryantm** [comment]
Okay, I think I fixed this by pinning nixpkgs and making a derivation/shell that incorporates all the runtime dependencies. @bobvanderlinden please let me know if this works for you.
