### ISSUE TITLE
Not detecting updates to plata-theme

### ISSUE THREAD

**Issue by tadfisher** [ryantm/nixpkgs-update#120]
`plata-theme` has regular updates, and is hosted on GitLab, but I haven't seen PRs from the bot.

- Derivation: https://github.com/NixOS/nixpkgs/blob/d6b10a59d392bd2ebfa8a04fb9df6591c70436fe/pkgs/data/themes/plata/default.nix
- Repology: https://repology.org/project/plata-theme/versions
- Source repo: https://gitlab.com/tista500/plata-theme/

**Comment by ryantm** [comment]
@tadfisher From the logs:

```
2019-06-17T14:19:34 plata-theme 0.8.3 -> 0.8.4
2019-06-17T14:21:43 FAIL Received ExitFailure 1 when running
Raw command: nix-build --option sandbox true --option restrict-eval true --arg config "{ allowBroken = true; allowUnfree = true; allowAliases = false; }" -A plata-theme
Received ExitFailure 1 when running
Raw command: nix log -f . plata-theme
Standard output:

error: build log of 'plata-theme' is not available
```

r-ryantm logs are available at https://discourse.nixos.org/t/nixpkgs-update-r-ryantm-logs/1464/

**Comment by tadfisher** [comment]
Huh, looks like it fails on the `glib` dependency because it's an alias:

```
error: attribute 'glib' missing, at /home/tad/src/nixpkgs/pkgs/data/themes/plata/default.nix:43:5
```

Any reason to disallow aliases?

**Comment by tadfisher** [comment]
This is fixed anyway, so thank you for pointing me to the logs!

**Comment by ryantm** [comment]
> Any reason to disallow aliases?

We stopped allowing aliases because it allowed it to always use the primary name for the pull request. https://github.com/ryantm/nixpkgs-update/issues/37 It is a policy of nixpkgs to not use aliases within the source tree, and [OfBorg checks it too](https://github.com/NixOS/ofborg/issues/248).
