### ISSUE TITLE
Renable point release updates for gnome

### ISSUE THREAD

**Issue by worldofpeace** [ryantm/nixpkgs-update#131]
cc @jtojnar

**Comment by ryantm** [comment]
@worldofpeace We've been just allowing all gnome updates to go through during non-release periods. Is it possible to specify some version bounds, or do the gnome projects covered have different version schemes?

**Comment by jtojnar** [comment]
Well, preventing a minor version bumps would fix this for majority of packages. But there are still some non-core apps that did not update in time and it would be nice if repology could update them now:

https://repology.org/projects/?maintainer=jtojnar%40gmail.com&outdated=1&inrepo=nix_unstable

Also some of the libraries might slip through (GTK 3.24 only updates the patch version, libgnome-games-support does whatever.), so the time when GNOME bump PR is open would be the only criterion. Maybe we could include that as a part of conflicting PRs detection (hmm, do we have an issue for that?)

**Comment by worldofpeace** [comment]
Ahh, I thought that during non major release periods you just did point releases.

> But there are still some non-core apps that did not update in time and it would be nice if repology could update them now:

Right, I think in that case perhaps no prs to gnome are opened during active major release or if there's a conflicting gnome PR.

**Comment by ryantm** [comment]
> Maybe we could include that as a part of conflicting PRs detection (hmm, do we have an issue for that?)

We [skip updates](https://github.com/ryantm/nixpkgs-update/blob/ad2fd44fc3e5beda0a7dd2aebb5e9223a2875a2a/src/GH.hs#L170) where there already exists a PR by anyone with the exact title of PR nixpkgs-update would use.


Okay, I'll remove the Gnome blacklists before the next run I do.

**Comment by jtojnar** [comment]
> We [skip updates](https://github.com/ryantm/nixpkgs-update/blob/ad2fd44fc3e5beda0a7dd2aebb5e9223a2875a2a/src/GH.hs#L170) where there already exists a PR by anyone with the exact title of PR nixpkgs-update would use.

I am always surprised that we already support so many features. ❤️

Many updates are actually done as a part of a set. For example GEGL is regularly bumped with GIMP: https://github.com/NixOS/nixpkgs/pull/72386

**Comment by ryantm** [comment]
It should be too hard to better handle this case. I opened an issue for tracking it. https://github.com/ryantm/nixpkgs-update/issues/132
