### ISSUE TITLE
Download from cachix doesn't work on NixOS 19.09 unless performed as root

### ISSUE THREAD

**Issue by das-g** [ryantm/nixpkgs-update#134]
## To reproduce

1. Choose a [PR on NixOS/nixpkgs filed by r-ryantm](https://github.com/NixOS/nixpkgs/pulls?utf8=✓&q=is%3Apr+author%3Ar-ryantm). (These tend to be created by nixpkgs-update.) E.g., one of these:
   - https://github.com/NixOS/nixpkgs/pull/75313
   - https://github.com/NixOS/nixpkgs/pull/75316
   - https://github.com/NixOS/nixpkgs/pull/75341
2. In the PR description, expand "Instructions to test this update (click to expand)"
3. Copy the "download from Cachix" command line from there, e.g.
   ```bash
   nix-store -r /nix/store/cm3p4qb5kw3ihklx2fm6l53adflfv4k2-python3.8-funcy-1.14 \
     --option binary-caches 'https://cache.nixos.org/ https://r-ryantm.cachix.org/' \
     --option trusted-public-keys '
     r-ryantm.cachix.org-1:gkUbLkouDAyvBdpBX0JOdIiD2/DP1ldF3Z3Y6Gqcc4c=
     cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
     '
   ```
4. Paste the command into a non-root bash terminal on a NixOS 19.09, where that Nix store path isn't already available

### Expected behavior

* command succeeds
* some output like
   ```
   /nix/store/cm3p4qb5kw3ihklx2fm6l53adflfv4k2-python3.8-funcy-1.14
   ```
* the build result is now available in the local Nix store

### Observed behavior

* command fails (exit code `1`)
* output
   ```
   warning: ignoring untrusted substituter 'https://r-ryantm.cachix.org/'
   warning: ignoring the user-specified setting 'trusted-public-keys', because it is a restricted setting and you are not a trusted user
   don't know how to build these paths:
     /nix/store/cm3p4qb5kw3ihklx2fm6l53adflfv4k2-python3.8-funcy-1.14
   error: build of '/nix/store/cm3p4qb5kw3ihklx2fm6l53adflfv4k2-python3.8-funcy-1.14' failed
   ```
* the build result isn't available in the local Nix store

### Further observations

* If one prepends `sudo` or otherwise runs the command as root, it works.

_Originally reported by @davidak in https://github.com/ryantm/nixpkgs-update/issues/93#issuecomment-563078882_

**Comment by ryantm** [comment]
Thanks for the detailed report @das-g . This is Nix/NixOS behaving as expected. If you want to use a non-official binary cache, your user must be "trusted". You can fix this by adding yourself to the [`nix.trustedUsers` list ](https://nixos.org/nixos/options.html#nix.trustedusers).

I am leaving this issue open until I improve the documentation to include something about this.

**Comment by ryantm** [comment]
Okay, I added a note about this to the PR text. Please check it out @das-g!

**Comment by das-g** [comment]
A link to https://nixos.org/nixos/options.html#nix.trustedusers might be appropriate in that note. Otherwise it looks good to me.
