### ISSUE TITLE
Don't assume the source is Repology

### ISSUE THREAD

**Issue by ryantm** [ryantm/nixpkgs-update#140]
Thanks to @Synthetica9 we have a new high-quality source of new versions for GitHub packages. So we need to implement a way to know which source the versions were from and report that in the PR text.

**Comment by Synthetica9** [comment]
Perhaps we could change the input format from `<package> <current version> <new version>` to `<package> <current version> <new version> <source url>`, so for example:

```
sway 1.2 1.3 https://repology.org/project/sway/versions
``` 

or

```
sway 1.2 1.3 https://github.com/swaywm/sway/releases
```
