### ISSUE TITLE
Missing updated hash for i383

### ISSUE THREAD

**Issue by Gerschtli** [ryantm/nixpkgs-update#184]
Hey, your bot seems to miss updating the sha256 for 32 bit systems. For an example see https://github.com/NixOS/nixpkgs/pull/84641.

It occured several times in the past, which required me to create a separate PR to fix this. Maybe there is a way your bot could automatically handle this?

**Comment by jtojnar** [comment]
One possible fix is to add `updateScript` that updates all platforms:

https://github.com/NixOS/nixpkgs/blob/ff245d646ed23e4371953810e66bc47e0180420c/pkgs/applications/editors/sublime/3/common.nix#L131-L144

**Comment by ryantm** [comment]
Generally, if it detects there is more than one sha256 hash in a file it skips trying to update it, but it can't detect the slightly fancy way you set the hash here. I think passthru.updateScript is the way forward. I have an issue tracking adding a rewriter for running those https://github.com/ryantm/nixpkgs-update/issues/182

**Comment by ryantm** [comment]
I forgot to say, sorry for the inconvenience, Gerschtli.

**Comment by Gerschtli** [comment]
Ah okay, thank you, I'll try to write an updateScript, the documentation is not very good concerning how to write such a script. Do you have any pointer on how this could be written for this example?

**Comment by jtojnar** [comment]
`passhru.updateScript` is documented here https://nixos.org/nixpkgs/manual/#var-passthru-updateScript.

It is really just a script that obtains latest version number (e.g. from the website) and then updates the necessary attributes (you can use `sed`, or `update-source-version` tool like [sublime does](https://github.com/NixOS/nixpkgs/blob/ff245d646ed23e4371953810e66bc47e0180420c/pkgs/applications/editors/sublime/3/common.nix#L131-L144)).

**Comment by Gerschtli** [comment]
I wrote a script and added it in the package, thank you all!
