### ISSUE TITLE
Messages cut off in IRC due to newline character

### ISSUE THREAD

**Issue by cole-h** [ryantm/nixpkgs-update#189]
Last good message (Pacific Time)
```
2020-04-14 21:13:09     --      Notice({^_^}): [nixpkgs] @r-ryantm opened pull request #85261 → notejot: 1.6.0 -> 1.6.3 → https://git.io/Jfvmg
```

First bad message (Pacific Time)
```
2020-04-14 22:06:36     --      Notice({^_^}): [nixpkgs] @r-ryantm opened pull request #85267 → nix-zsh-completions: 0.4.3 -> 0.4.
```

The commits that happened between these two times are ed230936ac32eff0905ac8c1528c6ad748f246b7 and d3690e0f697258123b0f8b3bf805555d60f11aed.

This appears to be due to the fact that there are newlines in the title. If you `curl https://api.github.com/repos/NixOS/nixpkgs/pulls/85267 | jq '.title'`, you'll notice that it returns `"nix-zsh-completions: 0.4.3 -> 0.4.4\n"`, but if you run the same in `#85261`, you'll  notice a lack of `\n` at the end. I had a discussion on IRC with @samueldr and @infinisil ([here](https://logs.nix.samueldr.com/nixos/2020-05-02#1588388994-1588389544;)), and we came to the conclusion that Freenode probably drops `\n` and a single preceding character, expecting it to be the `\r` of CRLF (`\r\n`).

The most obvious (to me) solution is to strip `\n` from the PR titles. I would help, but I haven't had the time to dive into Haskell yet; sorry.

**Comment by samueldr** [comment]
(Fixed on the github-to-irc bridge)

 * https://github.com/samueldr/github-to-irc/commit/5189f778d8962210a8faf0cd58b8bc03f49583e2

Though this `\n` does sound like something that shouldn't be part of the PR title :).
