### ISSUE TITLE
Some better system for not submitting the same PR twice.

### ISSUE THREAD

**Issue by ryantm** [ryantm/nixpkgs-update#19]
Right now there is a problem where I'm submitting the same PR twice. I could blacklist the packages that are being updated in a different way, but I'd prefer some way of ignoring a particular version, instead of blacklist them outright.

https://github.com/NixOS/nixpkgs/pull/37195#issuecomment-373833170

**Comment by matthewbauer** [comment]
One way that might be easy: fail if autoupdate/$PACKAGE_NAME exists.

**Comment by ryantm** [comment]
It already does that: https://github.com/ryantm/nix-update/blob/master/up.sh#L43

**Comment by ryantm** [comment]
This problem has grown, now that we are both running this potentially at the same time.

**Comment by davidak** [comment]
Could you search for a PR with package name AND the new version in its title?

That way you would also find PRs from other people.

**Comment by ryantm** [comment]
This isn't much of an issue anymore, since it checks if a PR exists with the same name before making the PR.
