### ISSUE TITLE
Allow multiple updates per pull request

### ISSUE THREAD

**Issue by jtojnar** [ryantm/nixpkgs-update#211]
GNOME has periodic releases that update lot of software, it would be easier to review if they were grouped into a single pull request (maybe split into staging and master branches).

Packages that need updating in lockstep would also need this.

**Comment by ryantm** [comment]
@jtojnar When you are doing this kind of update do you use the updateScript command that operates on all the GNOME packages at once?

**Comment by jtojnar** [comment]
Currently I am running `nix-shell maintainers/scripts/update.nix --argstr maintainer jtojnar`. Ideally, we would add package collections to make the filtering more specific.

**Comment by ryantm** [comment]
Duplicate of #29
