### ISSUE TITLE
Can't run nixpkgs-update in NixOS

### ISSUE THREAD

**Issue by DamienCassou** [ryantm/nixpkgs-update#217]
```session
$ export GITHUB_TOKEN=$(pass-show-password.sh "api.github.com/DamienCassou^nixpkgs-review")
$ nixpkgs-update update "cypress 4.8.0 4.9.0"
nixpkgs-update: hub: startProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
$ nixpkgs-update version
nix (Nix) 2.3.6
```

**Comment by bhipple** [comment]
`hub` needs to be in your `$PATH`.  Perhaps we should wrap `nixpkgs-update` instead.

**Comment by ryantm** [comment]
Sorry, this is because I thought propagatedBuildInputs were available at runtime. We either need to wrap it or figure out how to patch the references to be nix store paths. I'd prefer the later but it's likely to take more woork.

**Comment by jtojnar** [comment]
We should be able to pass `-DHUB_PATH=foo` in `cpp-options` to Cabal and then use `LANGUAGE CPP` pragma and `HUB_PATH` constant in the code:

https://cabal.readthedocs.io/en/stable/installing-packages.html#cmdoption-setup-configure-prog-options
https://guide.aelve.com/haskell/cpp-vww0qd72#item-oh9ytz0p

But using C pre-processor is ugly.

Another thing that comes to mind is using Template Haskell to get the path from environment variable:

https://hackage.haskell.org/package/th-env

**Comment by ryantm** [comment]
th-env seems to work nicely!
