### ISSUE TITLE
Add more logging (retries?) around Cachix upload

### ISSUE THREAD

**Issue by ryantm** [ryantm/nixpkgs-update#224]
It seems that some of the recent Cachix uploads look like the succeeded in the logs but there is nothing in the cache. We need to add better logging around Cachix and possibly a retry mechanism.

https://dpaste.org/r6K5
https://github.com/NixOS/nixpkgs/pull/94361

cc @kiwi

**Comment by Kiwi** [comment]
```
    02:43:44 [kiwi@mvp-nixos ~]$ nix-store -r /nix/store/rgmgdmxb8xkwcc4z656payl8v8cyzkxd-simplenote-1.20.0 \
    >   --option binary-caches 'https://cache.nixos.org/ https://r-ryantm.cachix.org/' \
    >   --option trusted-public-keys '
    >   r-ryantm.cachix.org-1:gkUbLkouDAyvBdpBX0JOdIiD2/DP1ldF3Z3Y6Gqcc4c=
    >   cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
    >   '
    don't know how to build these paths:
      /nix/store/rgmgdmxb8xkwcc4z656payl8v8cyzkxd-simplenote-1.20.0
    error: --- Error --------------------------------------------------------------------------------------------------------------------------- nix-store
    error: --- Error --- nix-daemon
    build of '/nix/store/rgmgdmxb8xkwcc4z656payl8v8cyzkxd-simplenote-1.20.0' failed
```
(for posterity as dpastes gets deleted after a week)

**Comment by ryantm** [comment]
Cachix uploading feature has been removed, in favor of using the `cachix watch-store`, so this is no longer in scope. If there is a problem with cachix caching we need to open an issue at https://github.com/nix-community/infra
