### ISSUE TITLE
Incorrect derivation file sometimes

### ISSUE THREAD

**Issue by ryantm** [ryantm/nixpkgs-update#24]
Our new way of figuring out the derivation file is sometimes wrong. For example,

`libgit2` picked the specific version instead of the non-specific one: "libgit2_0_25: 0.25.1 -> 0.26.3"
https://github.com/NixOS/nixpkgs/pull/37474

Same for `isl` "isl_0_15: 0.15 -> 0.19"
https://github.com/NixOS/nixpkgs/pull/37453

cc @matthewbauer

**Comment by ryantm** [comment]
Maybe we can filter the list coming from `nix-env -qa` to remove things containing the `_\d+` regex.

**Comment by dotlambda** [comment]
How about just taking the shortest matching name?

**Comment by matthewbauer** [comment]
The ```libgit2``` issue should be fixable. We have two versions of libgit2 in Nixpkgs but we only want to update the newest one. Repology correctly disagnoses it on the website:

https://repology.org/metapackages/?search=libgit&maintainer=&category=&inrepo=nix_unstable&notinrepo=&repos=&families=&repos_newest=&families_newest=&outdated=on

(notice the "legacy" and "outdated" labels)

Maybe there is a way to only query the "outdated" ones from Repology API? Not too familiar with it.

On the other hand, isl isn't as easy to fix given how the file is structured.

Anyway the best solution right now I think is to just blacklist them. We don't have too many 'multiple versions, single name' anyway.

**Comment by matthewbauer** [comment]
> Maybe we can filter the list coming from nix-env -qa to remove things containing the _\d+ regex.

That won't work because the name of the attribute is still 'isl' and 'libgit2'. The issue is that the "OLD_VERSION" is wrong that we're getting from Repology.

**Comment by ryantm** [comment]
> Maybe there is a way to only query the "outdated" ones from Repology API?

Yes, I'm already doing that. Is there some bit of information we need that we don't get from this line?
```
libgit2 0.25.1 0.26.3
```

**Comment by matthewbauer** [comment]
It should be:

```
libgit2 0.26.0 0.26.3
isl 0.17.1 0.19
```

**Comment by ryantm** [comment]
Oh sorry, I see now that there are multiple entries for nixpkgs unstable. Yes, I think I can fix my repology api code to handle that better.

**Comment by matthewbauer** [comment]
Yeah looking at the API, the "status" code returned should be "outdated" (as opposed to "legacy").

**Comment by ryantm** [comment]
Fixed repology-api and checked the output matches what @matthewbauer said above.

**Comment by ryantm** [comment]
I added a check for version compatibility. It should give up trying to update an attrpath that contains an incompatible version string now.

**Comment by ryantm** [comment]
This is probably the correct file, but it got to it the wrong way, so it has the wrong attrpath: https://github.com/NixOS/nixpkgs/pull/40830/files

**Comment by ryantm** [comment]
I'm closing this in favor of having specific issues about each problem related to this.
