### ISSUE TITLE
chezmoi (buildGoModule) has 0 binaries checked

### ISSUE THREAD

**Issue by jhillyerd** [ryantm/nixpkgs-update#242]
My [chezmoi package](https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/misc/chezmoi/default.nix) always says `0 of 0 passed binary check by having a zero exit code` despite having a [binary in the bin dir](https://gist.github.com/r-ryantm/dbb62b4ce5a9284af37f5b1ad1068855).

Example update PR: https://github.com/NixOS/nixpkgs/pull/102327

I wasn't able to find any docs on how to tell update to test a specific binary, and it appears it should try to run everything in the bin directory.  What am I missing?

**Comment by ryantm** [comment]
@jhillyerd I think the binary checking is messed up right now! Fixing this is high on my priority list for this project.

**Comment by raboof** [comment]
Noticed this in https://github.com/NixOS/nixpkgs/pull/111836 as well

**Comment by raboof** [comment]
Proposed #255

**Comment by ryantm** [comment]
I've decided to stop doing binary checking
