### ISSUE TITLE
Slack is outdated; why is the update not triggered?

### ISSUE THREAD

**Issue by dschrempf** [ryantm/nixpkgs-update#251]
See https://discourse.nixos.org/t/package-availability-status/11123/3.

> From looking at the repology information for Slack, it is not clear to me why it wasn’t updated by r-ryantm. At least it did in the past. Maybe it would make sense to open an issue about it in the nixpkgs-update repository?

Slack is outdated, but according to https://repology.org/project/slack/versions and the bot should be informed about Slack being outdated.

Thanks for having a look at this!

**Comment by ryantm** [comment]
@dschrempf nixpkgs-update does not know how to update packages that have multiple hashes in the file. Slack has hashes for darwin and linux in the same file: https://github.com/NixOS/nixpkgs/blob/3c6230cdbfef341eda05b7b0dce06f42e6d48939/pkgs/applications/networking/instant-messengers/slack/default.nix

**Comment by ryantm** [comment]
That said, I don't see even an attempt to update slack in the logs https://r.ryantm/log/ which is weird.

**Comment by jtojnar** [comment]
The package also has an update script so nixpkgs-update should not care about the number of hashes, should it?

**Comment by ryantm** [comment]
@jtojnar Is correct, so it's just a supply side problem that I should look into.

**Comment by ryantm** [comment]
I've made a new update source for r-ryantm that is based on if a package has an updateScript so I expect the supply-side problem to be resolved.
