### ISSUE TITLE
Add label "1.severity: security" if old version is marked vulnerable on repology 

### ISSUE THREAD

**Issue by dotlambda** [ryantm/nixpkgs-update#252]
If the old version has associated CVEs that the newer version doesn't have, the label "1.severity: security" should be added to the pull request, such that the one merging knows to do a backport. We might consider adding "9.needs: port to stable" as well.

**Comment by ryantm** [comment]
It isn't within @r-ryantm's power to add labels to PRs, so I'm going to have to close this.
