### ISSUE TITLE
More flexible version check

### ISSUE THREAD

**Issue by raboof** [ryantm/nixpkgs-update#256]
The `weed version` command from the `seaweedfs` package outputs `version 30GB 2.34  linux amd64`

The regex used to determine whether the version occurs in the output is `/[^.]*${version}\.*\s*/`, which does not match the (IMHO reasonable) `weed version` output.

How about we check for something like `/.*\b${version}\b.*/s`? It *might* produce more false positives in some cases, but IMHO it seems worth it...

**Comment by ryantm** [comment]
Sure, let's try it!

**Comment by raboof** [comment]
I'll give this a go!
