### ISSUE TITLE
Tag 0.2.0?

### ISSUE THREAD

**Issue by chkno** [ryantm/nixpkgs-update#264]
Please consider creating git tags for release versions.  It really helps navigate the history & quickly answer questions like "How much has changed between the 0.2.0 release and HEAD?"

It looks like 0.2.0 was cut at 4adc0c183c10fa6746be5ce5950aae151b465a3b , which has the smallest diff with [the tarball on hackage](https://hackage.haskell.org/package/nixpkgs-update-0.2.0/nixpkgs-update-0.2.0.tar.gz):
![nixpkgs-update-diff-to-0 2 0](https://user-images.githubusercontent.com/1118859/121638321-9ff02d00-ca3f-11eb-90b0-45258e39814f.png)

**Comment by ryantm** [comment]
0.2.0 is tagged! https://github.com/ryantm/nixpkgs-update/tree/0.2.0 Thanks for tracking down which commit matches. That is also the same commit date as the date in the tarball on Hackage, so I think it is right. I'll try to tag releases better going forward.
