### ISSUE TITLE
What does it take for a package to be updateable

### ISSUE THREAD

**Issue by deliciouslytyped** [ryantm/nixpkgs-update#266]
Please document what a package description needs to do to be updateable by nixpkgs-update.
Does it have anything to do with the updateScript interface?
What do I need to do if I want a package to be updated?

Basically, what, as a packager, do I need to do?

**Comment by deliciouslytyped** [comment]
With respect to specific questions, it would be nice to have these answered:
- does it expect a src = fetch* in the expression?
- does it parse it?
- does it extract the values by evaluation? 
- how does it substitute the new values?
- can it handle separate json files such as the output of nix-prefetch-github?
- when should updateScript be used instead?

**Comment by nh2** [comment]
Same question from me: I noticed `srt` wasn't being updated.

Is it because it has

```
    homepage    = "https://www.srtalliance.org";
```

and should it point to github instead for `nixpkgs-update` to notice new releases?

The logic should be shortly explained in the README>

**Comment by domenkozar** [comment]
An FAQ entry pointing to https://r.ryantm.com/log/ would be a good start!

**Comment by ryantm** [comment]
I've made documentation about why a package fails to update: https://ryantm.github.io/nixpkgs-update/nixpkgs-maintainer-faq/#no-update. It doesn't answer all of @deliciouslytyped's questions, but it is a start.

**Comment by ryantm** [comment]
Closing this for now. If people think the above answers should be incorporated into the docs in some way, I'm open to suggestion and will reopen.

**Comment by nh2** [comment]
> If people think the above answers should be incorporated into the docs in some way, I'm open to suggestion

@ryantm I think they should, but to save time for now it would already be very helpful if the README (or other preferred entry point for learning) would link to you answer comment above: https://github.com/ryantm/nixpkgs-update/issues/266#issuecomment-906012613
