### ISSUE TITLE
rabbitmq stopped updating

### ISSUE THREAD

**Issue by Profpatsch** [ryantm/nixpkgs-update#268]
rabbitmq stopped updating after https://github.com/NixOS/nixpkgs/pull/103511 (3.8.9).

The newest version is `3.8.19`, so my best guess is that it sorts version strings lexicographically, and `3.8.19` < `3.8.9`?

**Comment by turion** [comment]
I manually bumped to 3.9.1. The current release is now 3.9.3, and both github releases as well as repology reflect this. So at least now it can't be that anymore.

**Comment by turion** [comment]
When I run it locally I get the right diff. `nixpkgs-update` doesn't terminate though. I don't know whether that's expected, I've never used it before.

**Comment by turion** [comment]
Ah, it terminated, but it just took really long (several minutes). Not sure what it's doing there. Not very useful either that way, in the time it took to run I can manually create 5 version bump PRs ;)

**Comment by ryantm** [comment]
What commandline flags did you run it with?

**Comment by turion** [comment]
I think I did `GITHUB_TOKEN=... nixpkgs-update update "rabbitmq-server 3.9.1 3.9.3"`.

**Comment by turion** [comment]
Huh, and suddenly it works again (https://github.com/NixOS/nixpkgs/pull/134489). I'm sure you did some magic there ;)

**Comment by ryantm** [comment]
I recently changed nixpkgs update to do GitHub updates parallel to Repology updates and fixed some bugs with UTF8 decoding. That might have done it.

**Comment by turion** [comment]
Sounds like we can close for now.
