### ISSUE TITLE
Better logs

### ISSUE THREAD

**Issue by piegamesde** [ryantm/nixpkgs-update#273]
First of all, I don't really understand the categories under https://r.ryantm.com/log/: "github", "pypi", "repology". Which folder contains what logs?

But my actual issue is that the logs show a chronological version of what the bot has done. Usually, this is not interesting: as a package maintainer, I want to look for my packages and what the bot has done about them. So some output format that allows for easy per-package filtering across multiple days would be cool. Of course, a web site for that would be even cooler :)

**Comment by ryantm** [comment]
@piegamesde would this directory structure work for you as a next step?

```
log-dir/
├── attrpath
│   └── 2021-09-01-old_version-new_version.log
└── attrpath2
    └── 2021-09-01-old_version-new_version.log
```

**Comment by piegamesde** [comment]
Yes, that would help. I think only doing `attr/date.log` would already be enough.

**Comment by piegamesde** [comment]
Is the logs site publicly documented anywhere. I think this is the first time I come back to this issue in search for the logs.

**Comment by ryantm** [comment]
@piegamesde Yes https://ryantm.github.io/nixpkgs-update/details/#details

**Comment by ryantm** [comment]
The logs now follow this suggested directory format.
