### ISSUE TITLE
false updates are generated

### ISSUE THREAD

**Issue by veprbl** [ryantm/nixpkgs-update#288]
https://github.com/NixOS/nixpkgs/pull/143489

The diff replaces base32 representation of the hash with the same has in SRI
```
# nix hash to-sri --type sha256 0448z8gyaxpgpnksg34lzmffj36jdpm0ir4xxa5gvzagkx0wk07h
sha256-8IDJQZ9P/f2K6p3kCOpt0gzpXP2UjKenve925R/6iBA=
```

**Comment by jerith666** [comment]
https://github.com/NixOS/nixpkgs/pull/143712 and https://github.com/NixOS/nixpkgs/pull/143302 are two other examples of this.  I caught the latter and did it correctly, but missed the former.  :-(

**Comment by ryantm** [comment]
Sorry and thank you for the reports. All these examples here should be fixed by https://github.com/ryantm/nixpkgs-update/commit/3e04183a3732735d90d1677c1047aae7395893cd
