### ISSUE TITLE
Re-enable native cachix update

### ISSUE THREAD

**Issue by Mic92** [ryantm/nixpkgs-update#291]
We want to get rid of [cachix-update.service](https://github.com/nix-community/infra/blob/ab9f4aa7754d5b3765d1a535cf03f2248a4fd4c3/roles/nix-community-cache.nix#L12) again because it is racy.
Can you add the cachix upload to nixpkgs-update again?

**Comment by ryantm** [comment]
﻿Mic92: I switched back to calling `cachix push`, so you can get rid of the service as you please.

**Comment by Mic92** [comment]
Dropped in https://github.com/nix-community/infra/pull/154
