### ISSUE TITLE
autorefactor nix files to use short hashes

### ISSUE THREAD

**Issue by milahu** [ryantm/nixpkgs-update#295]
for example, replace

```diff
-    sha256 = "sha256-xxxxxxxxxx";
+    sha256 = "xxxxxxxxxx";
```

but keep

```diff
     hash = "sha256-xxxxxxxxxx";
```

https://github.com/ryantm/nixpkgs-update/blob/c78b63b4432444f33e62709382c9c89ae85e9305/src/Rewrite.hs#L270

i dont speak haskell, so in naive python

```py
nix_src = '... sha256 = "sha256-xxxxxxxxxx"; ...'
nix_src_new = nix_src.replace(f'sha256 = "sha256-{oldHash}"', f'sha256 = "{Nix.sha256Zero}"')
if nix_src == nix_src_new:
  nix_src_new = nix_src.replace(oldHash, Nix.sha256Zero)
```

or is this too invasive?

**Comment by ryantm** [comment]
Right now, it uses whatever hash is provided by either `nix-build` or the updateScript. Also, I think `sha256 =` is the old format that nixpkgs is mostly trying to migrate away from, so I don't think I want to spend effort on working on it. I'm going to close this, but if someone really wants this feature and submits a PR we can probably include it.

**Comment by ryantm** [comment]
That's a good proposal, but I think not every fetcher supports hash.
