### ISSUE TITLE
"hash '0000000000000000000000000000000000000000000000000000' does not include a type"

### ISSUE THREAD

**Issue by tomfitzhenry** [ryantm/nixpkgs-update#303]
nixpkgs-update fails to update some packages, because the intermediate state of setting the hash to sha256Zero is an invalid state:
* Chatty https://github.com/NixOS/nixpkgs/blob/247c8a676abf100c47e5448dd6dc967c15dcbee6/pkgs/applications/networking/instant-messengers/chatty/default.nix#L40
    * https://r.ryantm.com/log/repology/chatty/2022-03-02.log
    * https://r.ryantm.com/log/repology/chatty/2022-04-08.log
* Codec2: https://github.com/NixOS/nixpkgs/blob/247c8a676abf100c47e5448dd6dc967c15dcbee6/pkgs/development/libraries/codec2/default.nix#L11
    * https://r.ryantm.com/log/repology/codec2/2022-02-11.log

Initially I thought the problem was that `hash` didn't set the hash type "sha256-", but I see in https://github.com/NixOS/nixpkgs/pull/168944/files that nixpkgs-update was able to generate `hash`.

**Comment by ryantm** [comment]
I believe this is fixed with https://github.com/ryantm/nixpkgs-update/commit/a376578dcf7b904734d9512d9e425179cca939c2
