### ISSUE TITLE
Mark @r-ryantm as a bot account

### ISSUE THREAD

**Issue by pSub** [ryantm/nixpkgs-update#310]
Currently, @r-ryantm appreas to be a "normal" user account that is controlled by a machine. Accounts associated with Github Actions are marked as a bot account (e.g. https://api.github.com/users/welcome[bot]). This has the advantage that the account is clearly marked as a bot account when it interacts and does not clutter the "For you" feed. On the other hand it seems that those bot accounts do not have a profile page which makes it very hard get an overview over their activity. 

Maybe there is a way to get the best of both worlds?

I'm not sure if this is the right place to open this issue. Please point me the right direction if it is out of place.

**Comment by ryantm** [comment]
I'm happy to do this if someone shows me how. I've looked in the settings a few times now (just now again), and can't figure it out.

**Comment by pSub** [comment]
I posted this question at https://github.community/t/transform-normal-user-account-into-bot-account/260291.
