### ISSUE TITLE
webex package is not updating

### ISSUE THREAD

**Issue by uvNikita** [ryantm/nixpkgs-update#312]
I added `passthru.updateScript` to webex package here https://github.com/NixOS/nixpkgs/pull/181211 in the hopes that r-ryantm bot will start to create PRs when new version of package is available, but this is not happening for some reason.

Am I missing something? Should I add webex package to some whitelist of packages to be updated?

Running this command works as expected:
`$ nix-shell ./maintainers/scripts/update.nix --argstr package webex`

**Comment by uvNikita** [comment]
I see that logs suddenly appeared (https://r.ryantm.com/log/webex/2022-08-17.log) and update fails with the following error:

> error: getting status of '/run/nixpkgs-update/worker': No such file or directory

Not sure what I can do to fix it.

**Comment by ryantm** [comment]
@uvNikita Glad it is showing up in the logs now! That new problem is a problem with the configuration of the infrastructure running r-ryantm/nixpkgs-update. I'll try to fix it.

**Comment by uvNikita** [comment]
Is there any update on this issue?

I don't see any new logs here since 2022-08-21: https://r.ryantm.com/log/webex
I presume it means that the bot hasn't tried to update the package yet? How often should I expect the bot to make the attempt?

**Comment by uvNikita** [comment]
I see bot created a https://github.com/NixOS/nixpkgs/pull/218860, so seems like the issue is fixed now.

**Comment by ryantm** [comment]
I guess the issue was that some updatescripts were causing evaluation errors which broke all updatescripts updates. Thanks for the report and sorry for the lack of response earlier.
