### ISSUE TITLE
Not updating GeoGebra

### ISSUE THREAD

**Issue by HHR2020** [ryantm/nixpkgs-update#314]
GeoGebra has two paralleled versions, GeoGebra 5 and GeoGebra 6. The former is named as geogebra and the latter named as geogebra6 in nixpkgs. The problem is that geogebra5 is the default version in nixpkgs but it is mistakenly recognised as geogebra6 by nixpkgs-update. Repology marked geogebra5 as outdated but it is still under maintainence.

https://repology.org/project/geogebra/versions
https://r.ryantm.com/log/geogebra6/2022-08-23.log

**Comment by ryantm** [comment]
The problem is that it runs
```ShellSession
nix edit geogebra6 -f .
```
on nixpkgs and that opens the geogebra default.nix file for some reason. Seems like a bug in `nix edit` at first glance.

**Comment by ryantm** [comment]
Ah, I looked at the source code for nix and found that it is determining which file the installable is from by looking at the position of the meta information, and for that derivation the meta information is being imported from the default geogebra. So, it should update fine if you copy the meta information into geogebra6.

**Comment by ryantm** [comment]
As for the Repology issue, the website has a feature for leaving comments about the status of versions.
