### ISSUE TITLE
Support `vendorHash` property for `buildGoModule`

### ISSUE THREAD

**Issue by brumhard** [ryantm/nixpkgs-update#332]
Currently, it looks like packages that use the property `vendorHash` instead of the old `vendorSha256` property of `buildGoModule` don't get updated properly.
For example:
- https://r.ryantm.com/log/gopass/2022-12-17.log
- https://r.ryantm.com/log/vhs/2022-12-15.log

Since it's now the default in the documentation example (https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/go.section.md)  it would be nice to also support the newer `vendorHash` property. It got introduced here: https://github.com/NixOS/nixpkgs/commit/0d5c464ad611c9d7b8ba20717591ad435404ebcf

**Comment by ryantm** [comment]
Done.

**Comment by 06kellyjac** [comment]
Thanks for adding this however vendorSha256 is still in use and https://github.com/ryantm/nixpkgs-update/commit/842a77386f252570283f29f8ee80113db94836a7 removed it

https://r.ryantm.com/log/open-policy-agent/2023-01-21.log

1235 matches for vendorSha256
485 matches for vendorHash

should the goal be to move everything else over to vendorHash?

**Comment by ryantm** [comment]
@06kellyjac that commit also changes the bot to move them over to vendorHash.

**Comment by 06kellyjac** [comment]
If so then what is with the error?
I may have picked the wrong commit

```
error: attribute 'vendorHash' missing

       at Â«stringÂ»:1:4:

            1| p: p.vendorHash
             |    ^
Received ExitFailure 1 when running
```
