### ISSUE TITLE
How to make this work with scala-cli?

### ISSUE THREAD

**Issue by kubukoz** [ryantm/nixpkgs-update#339]
Hi! First of all, thanks for making and maintaining this, the value is immense.

I'm trying to find out how to make nixpkgs-update automatically update scala-cli. The package has an updateScript attached, and it seems like this program runs it ([log](https://r.ryantm.com/log/scala-cli/2022-11-29.log)). However, it doesn't seem to open PRs, and the logs say:

```
Old version 0.1.16" not present in master derivation file with contents (...)
```

What follows is the [default.nix](https://github.com/NixOS/nixpkgs/blob/9b0ec1313b8f4c8bf30846cbca9fe6660263c029/pkgs/development/tools/build-managers/scala-cli/default.nix) for scala-cli. The version is indeed not there, as it lives in [a separate file (sources.json)](https://github.com/NixOS/nixpkgs/blob/9b0ec1313b8f4c8bf30846cbca9fe6660263c029/pkgs/development/tools/build-managers/scala-cli/sources.json) - can I somehow configure this program to make it aware of that supporting file?

**Comment by rhendric** [comment]
You don't need to! In December—after the linked log was generated—nixpkgs-update was enhanced to better support this sort of thing. You can see in [this log](https://r.ryantm.com/log/scala-cli/2022-12-24.log), for example, that the sources.json file is now being used for this particular check. You should get PRs in the future if a human doesn't submit them first.

**Comment by kubukoz** [comment]
It's happening! https://github.com/NixOS/nixpkgs/pull/221627

Thanks @rhendric :)
