### ISSUE TITLE
rename scripts to more clear name

### ISSUE THREAD

**Issue by davidak** [ryantm/nixpkgs-update#35]
ups.sh -> nixpkgs-update.sh (like discussed in https://github.com/ryantm/nix-update/issues/13)
up.sh -> ???
to-staging.sh -> ?-to-staging.sh

**Comment by ryantm** [comment]
Since we've ported to Haskell, this is no longer relevant. I'm expecting we'll want to work on naming the Haskell files better though too! :smiley:
