### ISSUE TITLE
SHA512 support

### ISSUE THREAD

**Issue by JamieMagee** [ryantm/nixpkgs-update#350]
sha256 and sha512 are supported in nixpkgs, but it looks like nixpkgs-update only supports sha256. See [this example][1] of an update which changed the package hash from sha256 to sha512.

I'm not expecting package hashes to be 'upgraded' to stronger hashes (though that would be nice) but I would expect an update for a package that uses sha512 to also use sha512.

[1]: https://r.ryantm.com/log/wasabibackend/2023-04-08.log

**Comment by SuperSandro2000** [comment]
> Nix itself supports md5, sha1,

Most fetchers no longer support md5 or sha1.

**Comment by JamieMagee** [comment]
> Most fetchers no longer support md5 or sha1.

True, but that wasn't my main point, and I'm not asking for md5 or sha1 support. Regardless, I've removed that from my issue to prevent any confusion.

**Comment by prusnak** [comment]
I agree that if a derivation uses sha512 type of hash instead of sha256, the update script should honor this choice and not downgrade to sha256.
