### ISSUE TITLE
Aliased attr-path got used instead of the primary one

### ISSUE THREAD

**Issue by ryantm** [ryantm/nixpkgs-update#37]
https://github.com/NixOS/nixpkgs/pull/38330#issuecomment-377956263

**Comment by jtojnar** [comment]
Is there a solution for this, unless we add canonical paths to each derivation? Maybe use the shortest path?

**Comment by ryantm** [comment]
A sort of dumb solution would be to filter out names on the LHS in https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/aliases.nix

**Comment by ryantm** [comment]
Even awesomer dumb solution, delete the aliases file while searching for the attr path.

**Comment by ryantm** [comment]
Even awesomer not dumb solution: set `config.allowAliases = false`.
