### ISSUE TITLE
package's homepage was changed, bot unable to download latest version for years

### ISSUE THREAD

**Issue by medv** [ryantm/nixpkgs-update#380]
`ephemeralpg` should go from `3.1` to `3.3` yet continuously fails.

log: https://r.ryantm.com/log/ephemeralpg/2024-01-08.log
package: https://repology.org/project/ephemeralpg/packages
source: https://github.com/eradman/ephemeralpg/
new homepage: https://eradman.com/ephemeralpg/
latest version source (instead trying and failing on old homepage url as per the above log): https://eradman.com/ephemeralpg/code/ephemeralpg-3.3.tar.gz

Let me know if I can do anything. Cool project!

**Comment by rhendric** [comment]
Nothing for nixpkgs-update to do here; you need to change the source in Nixpkgs.

**Comment by medv** [comment]
Ok, now I get it! Thanks
