### ISSUE TITLE
nixpkgs-update doesn't set correct version for unstable versions

### ISSUE THREAD

**Issue by kirillrdy** [ryantm/nixpkgs-update#387]
for packages with no stable release eg
https://github.com/NixOS/nixpkgs/pull/286660

according to recently updated https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-naming

version must start with a number, so correct version needs to start with "0-`

I had a quick search though code but couldn't find where to change :shrug:

**Comment by zowoq** [comment]
The package uses an update script so this isn't a nixpkgs-update issue, it needs to be fixed in nixpkgs.

> https://github.com/NixOS/nixpkgs/pull/286660
> Ran passthru.UpdateScript

> https://github.com/NixOS/nixpkgs/blob/a89c3b15a6109b1ac0e7200352b21ed17196530c/pkgs/by-name/ha/hare/package.nix#L136
> updateScript = unstableGitUpdater { };

> https://github.com/NixOS/nixpkgs/blob/a89c3b15a6109b1ac0e7200352b21ed17196530c/pkgs/common-updater/unstable-updater.nix#L82
> new_version="unstable-$commit_date"

**Comment by kirillrdy** [comment]
@zowoq thank you !

**Comment by jtojnar** [comment]
That should be resolved by https://github.com/NixOS/nixpkgs/pull/280501

**Comment by kirillrdy** [comment]
@jtojnar thank you as well, I have found that PR and going to help my best to resolve it
