### ISSUE TITLE
Lockfile-only updates are committed with "pkg: X -> X"

### ISSUE THREAD

**Issue by Ma27** [ryantm/nixpkgs-update#388]
Examples:
* https://github.com/NixOS/nixpkgs/pull/285824
* https://github.com/NixOS/nixpkgs/pull/285086
* https://github.com/NixOS/nixpkgs/pull/221502
* https://github.com/NixOS/nixpkgs/pull/221502

These appear to happen because the lockfile has changed, but no version update was made.
The commit message itself is an issue already, some kind of "pkg: update lockfiles" may be better.

Also, I'm wondering if these updates are truly necessary: NPM projects have lots of dependencies and many aren't worth to be updated so in case of e.g. meshcentral every time r-ryantm takes a look, it also seems to generate an update PR. So perhaps the proper resolution for this is to prevent the bot from doing these kinds of updates.

**Comment by rhendric** [comment]
I think it'd be reasonable to create a PR only if an update script changes the version of a package.
