### ISSUE TITLE
r-ryantm keeps creating the same PR

### ISSUE THREAD

**Issue by FliegendeWurst** [ryantm/nixpkgs-update#393]
Is there some way to avoid @r-ryantm creating multiple PRs for the same package update? In my case, I closed the first PR: https://github.com/NixOS/nixpkgs/pull/292670 since the update caused unacceptable build failures. @r-ryantm created a new PR for the same update a few days later: https://github.com/NixOS/nixpkgs/pull/293790, which I also closed. Just now, I also closed the third PR https://github.com/NixOS/nixpkgs/pull/294919 since I'm taking care of the update myself in another PR (https://github.com/NixOS/nixpkgs/pull/294939).

Is it intentional that @r-ryantm keeps creating the same PR for this package update? Is there some way to avoid this?

**Comment by rhendric** [comment]
If you mark a PR as draft instead of closing it, it won't create another one.
