### ISSUE TITLE
new version not found

### ISSUE THREAD

**Issue by quantenzitrone** [ryantm/nixpkgs-update#402]
nixpkgs-update/r-ryantm [doesn't find](https://r.ryantm.com/log/doge/2024-03-16.log) the new version of doge, although it is clearly there: https://github.com/Olivia5k/doge/releases/tag/3.8.0.

Can nixpkgs-update only use releases and not tags, if yes why?

**Comment by rhendric** [comment]
This is the update script's responsibility. The update scripts for Python need a lot of love right now; I tried to do this in https://github.com/NixOS/nixpkgs/pull/230747 but ran out of patience for arguing.
