### ISSUE TITLE
warn when submitting a similar, but not identical update, for the same pacakge

### ISSUE THREAD

**Issue by colemickens** [ryantm/nixpkgs-update#408]
Hi

The bot sent two PRs for the same upgrade:
* https://github.com/NixOS/nixpkgs/pull/300018
* https://github.com/NixOS/nixpkgs/pull/299897

One of them was merged, and it turns out it was the "wrong" one, resulting in a third PR to fix the hash:
* https://github.com/NixOS/nixpkgs/pull/301623

I've followed up upstream to see if this was the result of them moving the 0.26.0 tag.

It would be exceptionally cool if the bot could:
* notice that it has sent a PR for the same versionA->versionB upgrade
* close the original PR, and/or add a note/warning directing users to consider the newer PR

**Comment by zowoq** [comment]
The two bot PRs are for different packages and their `src` is from different repos?

**Comment by colemickens** [comment]
Oooof. Sorry for the noise. I feel pretty silly.
