### ISSUE TITLE
Should not create PR for github pre-release

### ISSUE THREAD

**Issue by jvanbruegge** [ryantm/nixpkgs-update#409]
The tool opened [this PR](https://github.com/NixOS/nixpkgs/pull/302010), which tries to update to a per-release: https://github.com/mkb79/audible-cli/releases/tag/v0.3.2b3

I am not sure why because [this function](https://github.com/ryantm/nixpkgs-update/blob/8060113acfbe3aa955698cde51cfd4250c640703/src/GH.hs#L240) should only return full releases

**Comment by zowoq** [comment]
> https://github.com/NixOS/nixpkgs/pull/302010
> Ran passthru.UpdateScript

The package uses an update script so this isn't a nixpkgs-update issue.

**Comment by jvanbruegge** [comment]
oh, sorry then
