### ISSUE TITLE
Feature request: option to disable updates for certain packages

### ISSUE THREAD

**Issue by eclairevoyant** [ryantm/nixpkgs-update#415]
Some packages should not be updated, for example version-specific variants. There should be some capability to mark these packages to avoid bot spam.

**Comment by eclairevoyant** [comment]
I see, thanks for explaining!

**Comment by zowoq** [comment]
Opened a PR to make this more visible, currently only seems to be documented via the skiplist. https://github.com/nix-community/nixpkgs-update/pull/417
