### ISSUE TITLE
Include changelogs in the PR body

### ISSUE THREAD

**Issue by jtojnar** [ryantm/nixpkgs-update#44]
- For GitHub projects, we could use [API](https://api.github.com/repos/NixOS/nix/releases)
- For other projects we could diff the `NEWS` (`CHANGELOG.md`) files in the tarballs before and after the update, keeping the added lines.

**Comment by Mic92** [comment]
That would be really useful. Currently I waste time to do this on my own for each package.

**Comment by ryantm** [comment]
Okay, the GitHub part of this is basically working. Though it needs some work on presentation, I think https://github.com/NixOS/nixpkgs/pull/42970

**Comment by Mic92** [comment]
Maybe linking to it should be good enough.

**Comment by ryantm** [comment]
Yes, let's try switching to linking.

**Comment by jtojnar** [comment]
Why does it fail for some packages (e.g. https://github.com/NixOS/nixpkgs/pull/44782)?

**Comment by ryantm** [comment]
For that one, the problem is the code is looking for the file extenion to be .tar.gz but it is .tar.bz2. I need to make it more flexible. I think there is some other separate problem with the GitHub API too that I haven't tracked down.

**Comment by Profpatsch** [comment]
Bump, this would be really great to have.

I’d also consider adding a field to the nixpkgs `meta` data.

**Comment by ryantm** [comment]
@Profpatsch I'm not sure adding a URL would be enough to get the changelog directly into the PR body. I suspect this will be a more incremental project, or something to work on with Repology. 

Do you have some particular project, group of projects, or hosting repository that you want to see the changelog for?

**Comment by jtojnar** [comment]
We really want that for GNOME. Most software has `${name}-${version}.news` or at least `${name}-${version}.changes` on their mirrors, see: https://download.gnome.org/sources/libgda/5.90/

**Comment by Profpatsch** [comment]
> Do you have some particular project, group of projects, or hosting repository that you want to see the changelog for?

rabbitmq just uses their release page: https://github.com/rabbitmq/rabbitmq-server/releases
But many other github repos use a `CHANGELOG` file instead. You could provide a link to the source code `CHANGELOG` file somehow, since you need the source code for building anyway.

**Comment by bhipple** [comment]
I'm inclined to say we should just link to `meta.changelog`, if it exists, rather than try to parse out the specific release notes.  For two reasons:

1. It's way simpler for `nixpkgs-update` implementation, since we don't have to parse/cleanup all kinds of differently formatted changelog and news files.

2. When I'm looking at the changelog of a project, I may need to look at a span of N releases, e.g. if we're updating from version 5 to 7, I don't just need 7's changelog, I need 6's too.  While it's theoretically possible to do this in the bot too, it's much more straightforward if I just have a link to the whole news page of the project.

**Comment by jtojnar** [comment]
1. Simpler to implement, yes, but I am not convinced it is easier to use. Adding `meta.changelog` to everything is annoying and bloats the expressions slightly.
2. The `NEWS` file typically also contains changes from older releases.
3. I frequently check out old PRs and dig through their changelogs, linking to a news page (instead of specific state) leads to nowhere.
4. Projects on various forges (GitLab, Gitea) are not currently supported, diffing changelogs would be a 90% fallback until they are implemented.
Lot of projects do not have any URL

**Comment by ryantm** [comment]
@jtojnar Can we open a few separate more specific issues for handling various changelog sources?

**Comment by bhipple** [comment]
I think it's fine to have a link like this for `meta.changelog`:

https://gitlab.com/ita1024/waf/blob/master/ChangeLog

If I'm looking at a PR that says `waf: 2.0.19 -> 2.0.20`, I'm fine just getting that link.  Having well-formatted release notes inside the GitHub NixPkgs PR description itself would be even cooler, but handling all the broken edge cases sounds like a Sisyphean task, and the link is much nicer than nothing.
