### ISSUE TITLE
Pass "reviewers" to hub command

### ISSUE THREAD

**Issue by matthewbauer** [ryantm/nixpkgs-update#46]
Hub should support passing reviewers in the latest version:

https://github.com/github/hub/pull/1453

This would be useful to move the "maintainers" stuff here.

**Comment by jtojnar** [comment]
That would be nice but GitHubs seems to only allow requesting reviews from members or collaborators, not contributors, which many maintainers are.

**Comment by ryantm** [comment]
> Pull request authors and repository owners and collaborators can request a pull request review from anyone with write access to the repository.

https://developer.github.com/v3/pulls/review_requests/ 

I know a lot of maintainers have write access, but this doesn't seem worth doing to me. Closing now, but I'm happy to reopen if someone disagrees.

**Comment by srhb** [comment]
Is there some other way to ping reviewers that's directly visible from the PR overview? I'm a bit tired of opening PR's only to find reviewers have already been pinged. :D

**Comment by ryantm** [comment]
Is "PR overview" the list of PRs? I'm not sure what are all the things that GitHub shows there. You could assume that r-ryantm has properly pinged all the maintainers of a package; however, not every package has maintainers.

**Comment by srhb** [comment]
Yes, I meant the PR list. :) And okay, shame that Github doesn't expose something better for it. Oh well, can't have everything!
