### ISSUE TITLE
build results not found on cachix

### ISSUE THREAD

**Issue by xeji** [ryantm/nixpkgs-update#58]
When I try to use cachix (great feature!) as per instructions in r-ryantm's PRs, build results are not found on cachix. Accessing them directly via curl fails too.

I tried a few of r-ryantm's PRs and could not find any results on cachix.
Maybe the build results aren't pushed, maybe I'm doing something wrong here...

#### Example (nixpkgs PR #43028): 

store path is `/nix/store/hk60glvzvq8psbzxj585dy6q6dhyl0ig-eom-1.21.0` but 

```
$ curl -i https://r-ryantm.cachix.org/hk60glvzvq8psbzxj585dy6q6dhyl0ig.narinfo
HTTP/1.1 404 Not Found
 ```

#### Expected result 
similar to this (for cachix itself):

```
$ curl https://cachix.cachix.org/fgqfmzv1vzb60041sqwb1sprnw456v7r.narinfo
StorePath: /nix/store/fgqfmzv1vzb60041sqwb1sprnw456v7r-cachix-0.1.0.1
URL: nar/bb4f7c671e49346b1bbc12e4ffbc9415c56b8aae99cec6ca4e26176c2b2f3e46.nar.xz
Compression: xz
FileHash: sha256:bb4f7c671e49346b1bbc12e4ffbc9415c56b8aae99cec6ca4e26176c2b2f3e46
FileSize: 1862008
NarHash: sha256:0qd3ij4b0f8r1gdzghkk2q4imr4pxbz60dagqi1jb5vsp07y6ms4
NarSize: 14738784
References: 14nlrnm6bv7z25c9ismlhc2mrxsriyq2-gmp-6.1.2 6r6hk0qq5jd8n0sbfmpri0wd7icszi16-gcc-7.3.0-lib d0az5vfrk5cm65wcvxmfj2hjk613k9ni-xz-5.2.4 fr9a6l744pzn2nc68ayksl1v4400r27w-ncurses-6.1 gf00m2nz8079di7ihc6fj75v5jbh8p8v-zlib-1.2.11 pr73kx0cdszbv9iw49g8dzi0nqxfjbx2-glibc-2.27
Deriver: w8qqbm6mdnlka134x3iffnw3rg62l1l0-cachix-0.1.0.1.drv
Sig: cachix.cachix.org-1:KbOwKbc+zE5/MG+kTjNHjA789Rg5N0EZmACfaiX7kOLlfzhRpTjqNVVpq8fvPwOrvYUWsghLff8m8dSC9St4Ag==
```

**Comment by ryantm** [comment]
Yes, Infinisil noted this too. Thanks for making an issue for it. I'll try to fix it soon.

**Comment by ryantm** [comment]
@xeji Okay, new PRs should be fixed. Thanks for trying out the Cachix feature. Let me know if it actually works for you!

**Comment by ryantm** [comment]
cc @infinisil

**Comment by xeji** [comment]
Thank you @ryantm, works for me now :+1:

**Comment by Infinisil** [comment]
Yeah it works, awesome!
