### ISSUE TITLE
publish list of apps which the bot failed to upgrade?

### ISSUE THREAD

**Issue by volth** [ryantm/nixpkgs-update#61]
Is it possible to publish list of apps which the bot failed to upgrade and which need a bit of a human attention?

Sorted by repology's spread or by another metric pointing that "majority of distros have a newer version".

It could draw attention to the cases like https://repology.org/metapackage/libxklavier/versions or even https://repology.org/metapackage/xorg-server/versions

**Comment by ryantm** [comment]
Here log of the latest run: https://gist.github.com/ryantm/4d9ae8b39a50cf14461b7d321473d03c Where do you think I should publish it?

**Comment by volth** [comment]
> Where do you think I should publish it?

GIST is ok.
First I though about a bot-updated ticket, but GIST might be better because it has history

**Comment by volth** [comment]
The failures with ```"Reversed (or previously applied) patch detected!  Assume -R? [n]"``` mean the patches are accepted by upstream, it should be easy to upgrade by removing the patch from nix-file

**Comment by ryantm** [comment]
Okay, I'll manually keep https://github.com/ryantm/nixpkgs-update/issues/62 up to date with the latest log gist for now.

**Comment by jtojnar** [comment]
It would be nice to also have just a list of attributes, perhaps with a phase it failed in, maintainers and link to the corresponding line in the log. GitHub pages also might be a better place to host it.

**Comment by volth** [comment]
> Here log of the latest run: https://gist.github.com/ryantm/4d9ae8b39a50cf14461b7d321473d03c 

What does the error mean? I remember ```mercurial```s before ```4.5.2``` were updated automatically 
```
2018-07-13T06:41:54 mercurial 4.5.2 -> 4.6.2
2018-07-13T06:41:55 Update branch already on origin.
2018-07-13T06:41:55 FAIL
```

**Comment by ryantm** [comment]
It means there is a branch for mercurial in r-ryantm's GitHub repository that isn't deleted. It doesn't try to make updates if there is already an existing branch to avoid making two updates for the same package. 

https://github.com/r-ryantm/nixpkgs/tree/auto-update/mercurial
https://github.com/NixOS/nixpkgs/pull/37219

Looks like it can be deleted; so I deleted it.

**Comment by volth** [comment]
It should be ok to add a new commit to the existing branch.
If there is a pending PR, it will have 2 commits ("prog: 1.0 -> 2.0" and "prog: 2.0 -> 3.0")

**Comment by ryantm** [comment]
Yes, that sounds good but will require some somewhat major reworking of how it does things.
