### ISSUE TITLE
Commit messages aren't wrapped at 72 characters

### ISSUE THREAD

**Issue by catern** [ryantm/nixpkgs-update#66]
This makes it unreadable when viewed in a terminal or with other tooling. Wrapping at 72 lines is standard practice for git. Please change this soon before too many ugly commit messages make it in to nixpkgs :)

**Comment by jtojnar** [comment]
On the other hand, wrapped lines make it ugly when reading the commit messages in a proportional typeface. Do modern terminals not support wrapping lines?

**Comment by catern** [comment]
Terminals of course support wrapping lines, but having a single line spread across your entire screen is not very attractive.

Perhaps a more compelling point is that wrapping at 72 characters is a very common practice. See https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html for some comments about it. Defying this common practice requires some strong justification.

**Comment by ryantm** [comment]
@bjornfor also requested this. I am planning to do make this change.

**Comment by jtojnar** [comment]
Then we will need to have different `commitMsg` for `Git.commit` and `prMessage` as GitHub PRs are primarily displayed in a web browser and 72 characters would be extremely annoying there.

**Comment by ryantm** [comment]
Thanks for pointing that out jtojnar. I forgot about that and fixed it too now.
