### ISSUE TITLE
Check if an update is in staging already

### ISSUE THREAD

**Issue by Mic92** [ryantm/nixpkgs-update#69]
Gdb was merged in staging: 
  https://github.com/NixOS/nixpkgs/pull/44564
and the bot tried to merge it into master as well:
  https://github.com/NixOS/nixpkgs/pull/45235
  https://github.com/NixOS/nixpkgs/pull/44780

This probably does not happen too often, but it would be nice to have to detect this at some point.

**Comment by jtojnar** [comment]
It already does check: https://github.com/ryantm/nixpkgs-update/blob/15f16444caed45b7da82f6b453c8923fa9340437/src/Update.hs#L144-L149. not sure what went wrong.

**Comment by ryantm** [comment]
I only update the branches every hour or so, but this is off by about 11 days, so probably something is wrong. I'll try to look into what's going on.

**Comment by ryantm** [comment]
Another issue like this: https://github.com/NixOS/nixpkgs/pull/50738

**Comment by ryantm** [comment]
Another instance of the issue https://github.com/NixOS/nixpkgs/pull/50821

**Comment by ryantm** [comment]
https://github.com/NixOS/nixpkgs/pull/50827 similar issue

**Comment by ryantm** [comment]
Work on this will be related to #91

**Comment by ryantm** [comment]
Example of problem https://github.com/NixOS/nixpkgs/pull/53345

**Comment by ryantm** [comment]
Yay, I finally figured out the cause of this bug! The issue is that when it checks for the old version being on staging or master, it only does a sub-string check. So in the case of `gdb`, it checked if 8.2 is in the derivation file, and of course it is because 8.2 is a sub-string of 8.2.1.
