### ISSUE TITLE
Command to test package could be simpler

### ISSUE THREAD

**Issue by mpickering** [ryantm/nixpkgs-update#73]
Intead of the complicated cloning and checkout logic, you can instead pass the right tarball directly to `nix-shell`.

For example,

```
nix-shell --pure -I nixpkgs=https://github.com/r-ryantm/nixpkgs/archive/a4337af2012930ee15ba87f236b6ba9201d2d238.tar.gz -p openorienteering-mapper
```

**Comment by ryantm** [comment]
Thanks for the suggestion, and I'm excited about how much easier it will be for people to test the updates!
