### ISSUE TITLE
Add version incompatibility whitelist

### ISSUE THREAD

**Issue by ryantm** [ryantm/nixpkgs-update#88]
Example of a package that would benefit 
https://discourse.nixos.org/t/nixpkgs-update-r-ryantm-logs/1464/5?u=ryantm

**Comment by ryantm** [comment]
@layus Actually a better solution might be to ignore the version incompatibility, if the old version is also incompatible!

**Comment by layus** [comment]
Well, that's a start indeed. There are pitfals in some cases, but I am sure you are well aware of them ;-)

**Comment by ryantm** [comment]
Yes, it is still possible for a non-version-pinned package to be on a version that matches its suffix number and this can cause a false positive if the version upgrades beyond that suffix number.
